name: "Build Documentation"
on:
  push:

jobs:
  runPandoc:
    runs-on: ubuntu-18.04
    container: rstropek/pandoc-latex

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Run pandoc
        run: pandoc project-request.md -o project-request.pdf

      - name: "Archive PDF as artifact"
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: project-request.pdf
