name: "Backend Workflow"
on:
  push:

jobs:
  buildBackendJob:
    runs-on: ubuntu-18.04
    name: "Build Backend"
    steps:
      - name: "Some output"
        run: echo "Hello World"

      - name: "Checkout current source code"
        uses: actions/checkout@v2

      - name: "Setup Node Environment v12"
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: "Output node version"
        run: node -v

      - name: "Install Node dependencies"
        run: npm ci

      - name: "Execute build"
        run: npm run build --if-present

      - name: "Configure Hostname"
        run: echo "127.0.0.1  demo.app.info" | sudo tee -a /etc/hosts

      - name: "Debug etc/hosts"
        run: cat /etc/hosts

      - name: "Docker debug"
        run: docker ps

      - name: "Execute test"
        run: npm test

      - name: "Output working dir"
        run: pwd && ls -la

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Strong123!
          MSSQL_PID: Express
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Strong123! -Q \"SELECT 1\" || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
